export const REQUEST_SUBREDDIT = 'REQUEST_SUBREDDIT';
export const REQUEST_SUBREDDIT_SUCCESS = 'REQUEST_SUBREDDIT_SUCCESS';
export const REQUEST_SUBREDDIT_FAILURE = 'REQUEST_SUBREDDIT_FAILURE';
export const SHOW_DETAIL = 'SHOW_DETAIL';
export const HIDE_DETAIL = 'HIDE_DETAIL';
